### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Deewiant** [kode54/psflib#2]
There's no license in the repo nor in the source files, so the code's legal status is "all rights reserved". See e.g. https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license — "nobody else may reproduce, distribute, or create derivative works from your work". I'm assuming that that's not the intention.

**Comment by kode54** [comment]
I have added a license. Hopefully the MIT license is acceptable.

**Comment by Deewiant** [comment]
That's great, thanks!
