### ISSUE TITLE
What's your preferred platform for contributions and issue tracking?

### ISSUE THREAD

**Issue by jprjr** [kode54/psflib#9]
Hi there, just wanted to ask - there's copies of this repo here, on bitbucket, and https://git.lopez-snowhill.net/.

The foobar2000 components pages for the PSF decoder, GSF decoder, etc list the https://git.lopez-snowhill.net/ URL, so I created an account, but it looks like I'm unable to fork repositories.

What's your preferred platform(s) for accepting contributions and tracking issues? I opened identical PRs on here and bitbucket, happy to work on whichever your preferred platform is.

**Comment by kode54** [comment]
I can approve your account on my personal Gitlab, but here is fine so long as I remember to update this copy every time I touch that one there.
